---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@mail.com  # Your email for Let's Encrypt account
    privateKeySecretRef:
      name: ca-issuer-key  # Cert-Manager will create this secret
    solvers: 
      - http01:
        ingress:
          class: nginx 