apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-tls
spec:
  secretName: nats-tls  # Cert-Manager will create this secret for the certificate
  commonName: nats.io
  dnsNames:
  - nats.io
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
