apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: global
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.15.3
      helm:
        releaseName: cert-manager
        parameters:
          - name: installCRDs
            value: 'true'
    # - repoURL: https://github.com/eliblurr/argo-apps.git
    #   targetRevision: main 
    #   path: clusters/k3d-sandbox/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true      
    syncOptions:
      - Validate=false
      - CreateNamespace=true