---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster-apps
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/eliblurr/**'
    - 'https://nats-io.github.io/k8s/helm/charts/'
    - 'https://charts.jetstack.io'
  destinations:
  # Do not allow any app to be installed in `kube-system`  
    - namespace: '!kube-system'
      name: 'in-cluster'
      server: '*'
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'  

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: 'global'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'      

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-dev-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Front Office Infrastucture Dev Applications
  orphanedResources:
    warn: false
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - '*'