---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster-apps
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/eliblurr/**'
    - 'https://nats-io.github.io/k8s/helm/charts/'
    - 'https://charts.jetstack.io'
  destinations:
  # Do not allow any app to be installed in `kube-system`  
    - namespace: '!kube-system'
      name: 'in-cluster'
      server: '*'
    - namespace: '*'
      server: '*'
