name: Set Global Environment Variable

on: 
  push:
    branches:
      - uat/*
      - prod/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: ASdsaSDASD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert repository name to lowercase and set as global environment variable
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Print run ID with suffix
        run: | 
          echo "Run ID with suffix : ${{ github.run_id }}-${{ contains(github.ref_name, 'prod/') && 'release' || contains(github.ref_name, 'uat/') && 'prerelease' || 'dev' }}"

      - name: Print the repository name in lowercase
        run: 'echo "Repository name in lowercase: $REPO_NAME"'

      - name: Convert Env repository name to lowercase and set as global environment variable
        run: |
          echo "REPO=$(echo ${{ env.REPO }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # $(echo ${{ env.REPO }} | tr '[:upper:]' )

      - name: Global - Print the repository name in lowercase
        run: echo ${{ env.REPO }}
